name: lifesync_ai
description: "AI powered alarm app with smart unlocks and wallet (future UPI Auto-Cut Locked)"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  audioplayers: ^6.0.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
