name: lifesync_ai
description: A full-featured AI alarm app with UPI penalty, streaks, coins, and unlock modes.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.2
  timezone: ^0.9.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/alarm.mp3
    - assets/qr.png
